# ==========================================
# STAGE 1: Builder
# ==========================================

# We use a standard Node Alpine image as our secure base
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install ALL dependencies
RUN npm ci

# Copy the rest of the application codebase
COPY . .


# ==========================================
# STAGE 2: Runner (Production Image)
# ==========================================