# Defines which Docker Compose file format version we are using
# Version 3.8 supports modern Docker features like services, volumes, and health checks
version: "3.8"

# "services" contains all the containers/apps that Docker will create and run
# Each service is usually one container (example: API, database, frontend)
services:
  # "api" is the name of our service
  # We can use this name to refer to this container inside Docker
  api:

    # "build" tells Docker that it needs to create an image for this service
    build:

      # "context" tells Docker where to look for files needed to build the image
      # "." means use the current folder
      context: .

      # "dockerfile" tells Docker which Dockerfile to use for building
      dockerfile: DockerFile

    # "container_name" gives our running container a custom name
    container_name: devops-api

    # "ports" connects our computer port with the container port
    # Format: "computer_port:container_port"
    ports:
      - "3000:3000"

    # "environment" stores variables that our application can read
    # These values are passed into the container
    environment:

      # Sets the app mode to development
      - NODE_ENV=development

      # Tells our app which port it should run on
      - PORT=3000

    # "command" replaces the default Docker command
    # This runs when the container starts
    # Here it starts our development server
    command: npm start

    # "volumes" connects files/folders between our computer and container
    # This allows live updates without rebuilding the image
    volumes:
      
      # Mounts the current project folder into /app inside the container
      - .:/app

      # Creates a separate container folder for node_modules
      # Prevents local computer node_modules from replacing container ones
      - /app/node_modules


    # "healthcheck" lets Docker check if the application is working
    healthcheck:

      # "test" is the command Docker runs to check the app status
      # It sends a request to our health endpoint
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/healthz"]

      # How often Docker performs the health check
      interval: 30s

      # Maximum time Docker waits for the health check response
      timeout: 5s

      # Number of failed checks before Docker marks the container unhealthy
      retries: 3